# .streamlit/config.toml

[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#0A6AFF"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[browser]
gatherUsageStats = false

