AZURE_API_KEY = "1FWyRrTSAY3LJj8OP0GPUF9lPEfBu5N0q9TAASwfFWmRjW8oUe9OJQQJ99BFACfhMk5XJ3w3AAAAACOGJTyE"
AZURE_ENDPOINT = "https://l0016-mc8a7vkf-swedencentral.cognitiveservices.azure.com/"
DEPLOYMENT_NAME = "gpt-4o"
API_VERSION = "2024-12-01-preview"

form_endpoint = "https://scan-me.cognitiveservices.azure.com/"
form_key = "FJpkrHGa9Ffkz48Ao8ljygT6MIMqI0iRVaGBD2qx5fOaa0PNly1zJQQJ99BFACYeBjFXJ3w3AAALACOGatJQ"

openai_key = "1FWyRrTSAY3LJj8OP0GPUF9lPEfBu5N0q9TAASwfFWmRjW8oUe9OJQQJ99BFACfhMk5XJ3w3AAAAACOGJTyE"
openai_endpoint = "https://l0016-mc8a7vkf-swedencentral.cognitiveservices.azure.com/"
model_name = "gpt-4o"
deployment_name = "gpt-4o"
openai_version="2024-12-01-preview"

